# ARC Runner Scale Set Helm values - Large runners
# Chart: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set

githubConfigUrl: "https://github.com/DO-Solutions/demo-github-arc-doks"
githubConfigSecret: github-arc-secret

runnerScaleSetName: "doks-large"

minRunners: 0
maxRunners: 5

containerMode:
  type: dind

template:
  spec:
    nodeSelector:
      node-role: jobs
    tolerations:
      - key: "node-role"
        operator: "Equal"
        value: "jobs"
        effect: "NoSchedule"
    priorityClassName: arc-runner
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        resources:
          requests:
            cpu: "1800m"
            memory: "3500Mi"
          limits:
            cpu: "1800m"
            memory: "3500Mi"
