apiVersion: v1
kind: Namespace
metadata:
  name: arc-systems
  labels:
    app.kubernetes.io/part-of: arc
---
apiVersion: v1
kind: Namespace
metadata:
  name: arc-runners
  labels:
    app.kubernetes.io/part-of: arc
